cncf/landscapeapp

src/styles/itemModal.scss
Fixes #193 
It seems that the original idea was to show larger arrows on mobile and hide the carets shown on larger screens. For some reason the icon's class was changed and therefore we were showing both the large arrow and the carets. The fix is to hide the caret's svgs on mobile
=> Fix double arrows appearing on modals on mobile

tools/generateJson.js, tools/validateLandscapeKeys.js
Implements #269 
Adding `open_source: false` to `landscape.yml` will force the project not to be open source.
=> #269 Add option for non-open source projects in landscape.yml

tools/githubDates.js
Fixes hanging when fetching data about https://github.com/gentoo/gentoo
* Use Github API to find a repo's first commit, instead of crawling Github UI.
* Find latest release by querying  `https://api.github.com/repos/${repo_name}/releases` and getting the first item on the list. This avoids getting a `404` when calling  `https://api.github.com/repos/${repo_name}/releases/latest`
=> Improvements to fetching data from github API

.npmrc
Generated output by `npm install`
```bash
$ npm install
[fsevents] Success: "/Users/jordi/workspace/landscapeapp/node_modules/fsevents/lib/binding/Release/node-v67-darwin-x64/fse.node" is installed via remote
info sharp Using cached /Users/jordi/.npm/_libvips/libvips-8.7.4-darwin-x64.tar.gz
Downloading Chromium r674921 - 108.3 Mb [====================] 100% 0.0s
Cached binary found at /Users/jordi/.npm/node-sass/4.12.0/darwin-x64-67_binding.node
(node:24735) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGINT listeners added. Use emitter.setMaxListeners() to increase limit
Binary found at /Users/jordi/workspace/landscapeapp/node_modules/node-sass/vendor/darwin-x64-67/binding.node
Testing binary
Binary is fine
added 2100 packages from 1076 contributors and …
```
=> Set npm loglevel to silent; closes #277

src/components/ItemDialogContent.js
Related to #273.
Sandbox labels will come from `settings.yml` instead of being hardcoded.
=> Get Sandbox Label from settings.yml

src/components/App.js, src/components/CustomAutoSizer.js, src/components/HomePage.js, src/styles/theme.scss, src/utils/browserZoom.js
When user zooms in on mobile (or tablet), change the landscape to have auto width and height (as opposed to fixed width and height) and move the scrolling to the outer page.
=> Fix mobile zooming; Fix #345

src/components/InternalLink.js, src/components/ItemDialogContent.js, src/reducers/mainReducer.js, src/types/fields.js, src/utils/syncToUrl.js, tools/generateJson.js
@dankohn , please notice this issues:
- in a filter panel, for a grouping select, nothing is selected when a `grouping=language` is used, because you want to hide that option
- we show 'No information' when it is a closed source project or languages are not available by github
- when you filter by a language and also group by a language, you may see that multiple groups are displayed. That is ok, although not obvious from a first glance, because grouping is done by the first language, and filter is done by any language in the project.
=> add grouping by a primary language, close #445

package.json, src/utils/saneName.js, tools/checkWrongCharactersInFilenames.js, tools/fixWrongCharactersInFilenames.js
I don't want to overengineer this.
This will prevent us from having wrong filenames in hosted_logos. When there are latinic non ascii characters, they will be replaced for cached_logos. If there are cyrillic or chinese symbols in cached_logos, and that happens only if a company name is chinese - we already do not allow such cases.
example error for hosted_logos:
```
Processing the tree
FATAL: please rename LLVMû.svg to LLVMu.svg
```
For omp-landscape, I'll remove  a cached_logo and then I'll commit a new version to the master
=> 387 fix ascii filenames

src/components/BigPicture/Elements.js, src/components/BigPicture/LandscapeContent.js, src/components/BigPicture/LandscapeInfo.js, src/components/BigPicture/OtherLandscapeLink.js, src/utils/syncToUrl.js
When zooming landscape, use CSS `transform: scale(${zoom})` instead of having to calculate height, width and position for every element.
`transform` is supported on every major browser: https://caniuse.com/#search=transform
=> Use CSS scale to zoom landscape

src/utils/browserZoom.js
Fix issues on Firefox when resizing. This was caused by the `isZoomed` function, which calls `window.visualViewport` which is undefined on Firefox. The function is only used to detect "pinched" zoom on mobile, so to fix this, the function will return `false` for desktop browsers.
=> Fix Firefox resizing

src/components/BigPicture/FullscreenLandscape.js, src/components/BigPicture/HorizontalCategory.js, src/components/BigPicture/LandscapeContent.js, src/components/BigPicture/OtherLandscapeLink.js, src/styles/theme.scss, src/utils/landscapeCalculations.js, tools/ciServer.js, tools/migrate.js, tools/renderLandscape.js
This is actually two changes in one. The first one is to stop using `fullscreen_size` for any calculations, given that it can be calculated more accurately from the contents of the landscape  
with:
```
width = inner landscape width + 40px padding (20px per side)
height = inner landscape height + 40px padding (20px per side) + 40px for the header
WHERE
inner landscape width = max(category.left + category.width) for all categories
inner landscape height = max(category.top + category.height) for all categories
```
This way of calculating the fullscreen size is preferable because it's accurate and it removes the potential for human error. As you can see below in the Previews section some landscapes had the wrong size and the content didn't fit. Other landscapes had weird margins on the right …
=> Automatically calculate optimal full screen size

landscapes_dev/index.html, package.json, tools/addExternalInfo.js, tools/apiClients.js, tools/calculateNumberOfTweets.js, tools/crunchbase.js, tools/retry.js, tools/rpRetry.js, tools/updateProcessedLandscape.js, tools/updateTimestamps.js
Some improvements to the `npm run update` task. Mainly:
* Refactor `GithubClient` to get the rate limit and reset time from the response headers for the latest request, instead of having to query https://api.github.com/rate_limit every time we do a request. Instead of always waiting one hour if we hit the rate limit, this will wait whatever time we have left.
* Add a `YahooFinanceClient` that inherits from `ApiClient`. `ApiClient` allows two things: 1. not repeating a request twice and 2. not retrying a failed request when the failure was not caused by hitting a rate limit. We were retrying requests that were 404 which is unnecessary.
* I've also changed `npm run update` to add `updated_at` to `processed_landscape`. This way we can know when was the latest time that `npm run update` ran …
=> Improvements to npm run update

tools/apiClients.js, tools/crunchbase.js
To avoid having to manually fix stock tickers, use the exchange information that crunchbase provides to add the exchange suffix to the stock ticker.
For instance:
* PST becomes [PST.MI](https://finance.yahoo.com/quote/PST.MI)
* VOD becomes [VOD.L](https://finance.yahoo.com/quote/VOD.L)
* 6502 becomes [6502.T](https://finance.yahoo.com/quote/6502.T)
* 0700 becomes [0700.HK](https://finance.yahoo.com/quote/0700.HK)
* 000063 becomes [000063.SZ](https://finance.yahoo.com/quote/000063.SZ)
Note that this method needs to map an exchange provided by crunchbase to a suffix acceptable by Yahoo Finance. So if a new company is added that trades in an exchange we yet don't know, the request will fail until we add a valid mapping.
=> Automatically add exchange suffix to stock ticker

tools/crunchbase.js, tools/pruneExtraEntries.js
Couple of changes to find a few delisted stocks that were missed (RHT and NOKIA):
```diff
-              ticker: RHT
+              ticker: IBM.SW
```
```diff
-              ticker: NOKIA.HE
```
And to automatically remove null stock tickers when the stock from Crunchbase can actually be found:
```
Deleted null ticker for UCloud Kubernetes Service（UK8S) because the stock exists (688158.SS)
Deleted null ticker for UCloud (KCSP) because the stock exists (688158.SS)
Deleted null ticker for UCloud (member) because the stock exists (688158.SS)
Deleted null ticker for NEC (KCSP) because the stock exists (6701.T)
Deleted null ticker for NEC (member) because the stock exists (6701.T)
Deleted null ticker for Hitachi because the stock exists (6501.T)
Deleted null ticker for Hitachi Vantara (member) …
```
=> Improvements to finding delisted stocks [Fix #7]

tools/crunchbase.js
Output
```
Fetching crunchbase entries
******************************************************E*************************************************
Using cached entry, because can not fetch: red-hat Circular dependency detected: green-cross-pa-cameca-emeritus-director-keary-d-hayes-ii and danny-hayes-610e are parents of each other
```
=> Throw error when there's a circular dependency on Crunchbase

tools/addExternalInfo.js, tools/apiClients.js
This adds a global flag `skip_crunchbase` to the `global` section of a `settings.yml`
When a flag is present, usage of `crunchbase` field on item is prohibited, instead an `organization: {name: 'Org Name'}` is a proper way to specify the information about an organization.
Tested on a `test-no-crunchbase` of a finos-landscape
Example `settings.yml` is https://github.com/finos/finos-landscape/blob/test-no-crunchbase/settings.yml
Example `landscape.yml` is https://github.com/finos/finos-landscape/blob/test-no-crunchbase/landscape.yml , note that we do not use `crunchbase` entries there at all
=> 206 allow to skip crunchbase

src/components/BigPicture/FullscreenLandscape.js
On fullscreen landscape we autozoom the content to fit the window and center the content (this feature works on all browsers except Firefox). 
For very small landscapes the large zoom causes the layout to break. For instance on LFAI
This change limits the maximum amount of zoom, so the layout does not break.
=> Fix auto-zooming layout issues

src/utils/landscapeCalculations.js
Improvement to calculations done to assign columns to each subcategory, so that subcategories with only large items don't end up with an empty "small" column. This seems to affect only OMP:
Before:
After
=> Layout improvements

landscapes.yml
Now that LFN landscape is building successfully it can be added back.
This reverts commit 1dbe3395432b748a1058f71c54e0d5ea5b6b28e1.
=> Revert "Remove LFN landscape for now"

src/components/ItemDialogContentRenderer.js
This checks whether there are twitter keys are provided, and if not then hides the twitter button with the tweet count in the dialog box.
CC @michaelmoss @awright @GeriG966 @danielsilverstone-ct @apataru
=> Hide twitter button when no twitter key is provided
