cncf/landscapeapp

tools/removeQuotes.js
LGTM, checked locally via `PROJECT_PATH=../lfdl yarn remove-quotes`
=> reorder keys in settings.yml, close #6

tools/fetchImages.js
=> forgot to store a hash for local images, close #77

src/components/HomePageContainer.js, src/index.ejs
Signed-off-by: Dan Kohn <dan@dankohn.com>
=> Get title from settings

src/utils/syncToUrl.js
=> fix an embed mode, close #112

package.json, specs/main.spec.js
=> Fix intermittent tests, close #119

tools/reportToSlack.js
=> skip an initial part of log where yarn modules are installed, close #63

src/iframeResizer.js
Test if domcontentloaded wrapper is enough
=> add a dom content loaded wrapper

tools/checkLinks.js, tools/debugCheckLinks.js
=> fix error message in check-links, close #152

src/components/Summary.js
=> update a summary text, close #159

tools/checkLinks.js, tools/debugCheckLinks.js
Can not reproduce on tencent enterprise.html, now it returns `ok`, but I've added extra checks to prevent such false positives in future
=> prevent false positives from reporting, close #172

package.json
=> remove a babel warning, close #155

src/reducers/mainReducer.js, src/utils/csvExporter.js, src/utils/itemsCalculator.js
=> fix csv export, close #179

src/utils/itemsCalculator.js, src/utils/summaryCalculator.js
Ensure that number of rows in the exported file matches the number of rows from a summary description
=> update a summary calculator, close #179

tools/fetchGithubStartDate.js, tools/fetchGithubStats.js, tools/validateLandscapeKeys.js
We need to merge this first, then to check a PR for a new landscapeapp
https://github.com/cncf/landscape/pull/1143/files
=> strict validation of landscape.yml, fatal error on wrong github url, close #188

tools/addExternalInfo.js, tools/crunchbase.js
Do not merge yet, I'm making a full crunchbase fetch here
=> 190 fail on empty crunchbase city

tools/generateJson.js
=> ban spaces in certain fields, close #172

build.sh, full_build.sh, src/components/MainContent.js, src/components/MainContentContainer.js, src/reducers/mainReducer.js, src/styles/theme.scss, src/utils/syncToUrl.js, tools/addExternalInfo.js
PRs with new should include a test.
Note that https://www.crunchbase.com/organization/asyncy#section-overview does not have a city, I had to remove it from the list
=> (DO NOT MERGE YET) 200 - members in landscape.yml

src/styles/theme.scss
=> less space between example filters, close #215

full_build.sh, src/components/App.js, src/components/BigPicture/Elements.js, src/components/BigPicture/ExtraLandscapeContentContainer.js, src/components/BigPicture/FullscreenLandscape.js, src/components/BigPicture/LandscapeContent.js, src/components/BigPicture/MainLandscapeContentContainer.js, src/components/BigPicture/ThirdFullscreenLandscapeContainer.js, src/components/BigPicture/ThirdLandscapeContentContainer.js, src/components/BigPicture/index.js, src/components/HomePage.js, src/components/ItemDialogContent.js, src/reducers/mainReducer.js, src/types/fields.js, src/utils/itemsCalculator.js, src/utils/syncToUrl.js, tools/addExternalInfo.js, tools/crunchbase.js, tools/generateJson.js, tools/renderLandscape.js, tools/validateLandscapeKeys.js
=> DO NOT MERGE, 223 - members landscape support

src/components/BigPicture/SwitchButton.js, src/components/BigPicture/SwitchButtonContainer.js, src/styles/theme.scss
That is for a members landscape branch. Nothing should be broken when a master branch is used.
=> support abbreviation, #223

src/utils/itemsCalculator.js
=> push non public entries to the end in the card mode, close #234

tools/crunchbase.js
=> Do not duplicate Antarctica, close #235

_redirects
Signed-off-by: Dan Kohn <dan@dankohn.com>
=> Add redirects

.babelrc, npm-shrinkwrap.json, package.json, src/reducers/mainReducer.js, src/utils/itemsCalculator.js, src/utils/sharedItemsCalculator.js, src/utils/syncToUrl.js, tools/resolve-lookup.js, tools/resolve-preview.js, tools/resolve-settings.js, tools/sitemap.js
This should fix the sitemap, I choose a proper landscape prefix.
If the element belongs to no landscape, because, for example, we got rid of 'Cloud' section, it goes to the 'format=card-mode&selected=x'
No redirects yet.
=> fix sitemap so it adds a proper landscape prefix, close #249

src/index.ejs
=> redirect to / for wrong urls, close #210

tools/sitemap.js
=> return back pdfs to sitemap, close #266

src/utils/syncToUrl.js
I don't add a canonical link to '/', not sure if we need this.
=> adding a canonical link to all indexed pages, close #264

src/components/ItemDialogContent.js, tools/generateJson.js
This requires a 271 branch on a cncf project too.
=> support subsidiary project, treat it as a member project, close #271

src/types/fields.js
Fixes #218
Group URL filter params by top category.
=> #218 Fix URL filter params grouping

src/reducers/mainReducer.js, src/types/fields.js, src/utils/isGoogle.js
=> Support googlebot=yes on query string; closes #283

src/components/BigPicture/FullscreenButton.js, src/components/BigPicture/SwitchButton.js, src/components/BigPicture/ZoomButtons.js, src/components/CustomAutoSizer.js, src/components/HomePage.js, src/components/InternalLink.js, src/components/TweetButton.js, src/styles/theme.scss
Improvements to CSS responsiveness. Especially around positions of tweet button and landscape controls.
Gif resizing screen:
Appearance on iphone:
Appearance on ipad:
=> Improvements to CSS responsiveness; Fixes #246

src/components/ItemDialogContent.js, src/components/TwitterTimeline.js
| Before | After |
| --- | --- |
| <img src="https://user-images.githubusercontent.com/16135423/64965856-06adda00-d89e-11e9-9589-3937b980c014.png" alt="before" width="250" /> | <img src="https://user-images.githubusercontent.com/16135423/64965842-031a5300-d89e-11e9-84ab-faf7c71f97e0.png" alt="after" width="250" /> |
=> Fix broken layout in embedded twitter timeline; Fix #331

src/components/BigPicture/LandscapeInfo.js
Works in Chrome, but have not tried how good it is for FF and other browsers
=>  fix for a text zoom, close #378

README.md
=> Add examples of embedding

README.md
@dankohn readme updated, it was a popular cache invalidation issue.
=> help Dan to run his `yf` script without issue, close #416

tools/fatalErrors.js
Example - https://github.com/cncf/landscapeapp/pull/392#issuecomment-544393739
=> escape cncf bot messages, both html and markdown, close #414

tools/fundingHistoryData.js
=> ignore changes < $100, close #499

tools/apiClients.js, tools/fatalErrors.js, tools/getRepositoryInfo.js, tools/githubDates.js, tools/testRepoLatestDate.js
This adds a one hour delay when a github api quote is exceeded. Merging this to the master to check that a daily update works ok.
=> 506 fix latest commit date

src/components/ItemDialogContent.js, tools/addExternalInfo.js, tools/calculateNumberOfTweets.js, tools/fetchGithubStartDate.js, tools/fetchGithubStats.js, tools/generateJson.js, tools/getRepositoryInfo.js, tools/migrate.js, tools/processedLandscape.js, tools/removeQuotes.js, tools/repos.js, tools/resetTweetCount.js, tools/updateTimestamps.js, tools/validateLandscape.js
Support additional repos. They can be added to a landscape item using:
```yaml
additional_repos:
- repo_url: https://github.com/covid19risk/covidwatch-ios
branch: "master" (optional)   
```
For all repos, we will aggregate language stats, stars, contributors and contributions; get the smallest first commit date and the biggest last commit date.
=> Support additional repos [Fix #559]

landscapes.yml
=> Add lf-landscape to landscapes.yml

src/components/ItemDialogContent.js
=> add "commits" to Y axis in a chart, close #552

README.md
=> Tweak slightly so it will work with zsh as well.

README.md
=> Add VectorLogoZone as a source of SVGs

package.json, src/pages/404.js
* Add back `open:src` and `open:dist` so people don't need to update aliases
* Show redirected URL in warning message for deprecated URLs
=> Improvements to next switch

README.md
=> Add CloudConvert instructions and clean up section

README.md
=> Re-worked to be a central resource for landscape entries

landscapes.yml
=> Remove openjsf landscape

README.md
=> Update docs for #725 changes

README.md, src/components/ArrayFilterContainer.js, src/components/Filters.js, src/types/fields.js, src/utils/getPrerenderProps.js, src/utils/itemsCalculator.js, tools/generateJson.js
=> Filter organizations by company type and industries

landscapes.yml
=> Add LFN landscape

src/components/BigPicture/FullscreenLandscape.js, src/utils/useCurrentDevice.js
See #735 
This feature does not work on Firefox. And it's only intended for desktop browsers.
=> Autoscale fullscreen landscape to fit window [Close #735]

landscapes.yml
=> Update build hook for various landscapes moving from master to main

landscapes.yml
=> Add OpenSSF landscape

tools/crunchbase.js
=> Add Bolsa de Madrid

src/components/ItemDialogContentRenderer.js
The link of the first commit in the cards was broken because of `"` hence fixed it.
=> Fix the link of the First Commit
